{
 "title": "New dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Number of EC2 nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_node_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Jobs (Active + Pending)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kube_job_status_active)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Node CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(instance:node_cpu_utilisation:rate5m)",
     "legendFormat": "total"
    },
    {
     "expr": "instance:node_cpu_utilisation:rate5m",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Jobs breakdown by status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    { "expr": "sum(kube_job_status_active)", "legendFormat": "active + pending" },
    { "expr": "sum(kube_job_complete)", "legendFormat": "completed" }
   ]
  },
  {
   "title": "Cluster CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    { "expr": "sum(instance:node_num_cpu:sum)", "legendFormat": "capacity" },
    {
     "expr": "sum(instance:node_cpu:rate:sum)",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Containers by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum by (namespace) (kube_pod_container_info)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}